name: Test Action

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Inject Secrets
        uses: ./
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          # Fetch a secret with key "HELLO" and value "WORLD"
          secrets: |
            HELLO > HELLO

      - name: Check 
        if: ${{ env.HELLO != 'WORLD' }}
        run: |
          echo "::error title=Error::Secret was not fetched correctly"
          exit 1